### ISSUE TITLE
Warrior Deed Die

### ISSUE THREAD

**Issue by ckwk** [cyface/foundryvtt-dcc#33]
Not entirely sure how we want to handle the Deed Die in the Warrior character sheet.  If it were up to me, I would have there be a field that the user can populate within the "Warrior" tab that would apply itself ontop of any attack rolls done in the "Equipment" Tab.  

To fit more in line with the current design philosophy, however, there could be a field in the "Warrior" tab that can be populated with what the Deed Die is and then have a button that rolls it specifically.  Then, when they want to attack, they press the Attack button and it adds the value of the previously rolled Deed Die to their To Hit and Damage rolls.  That way, they know if they successfully do the Deed immediately as it is a separate roll.

**Comment by mooped** [comment]
It's part way there currently, though not easily discoverable.

The Attack Bonus field can be filled with an expression containing a dice roll (ie. the deed die) and "@ab" in the To Hit and Damage fields of a weapon expands to the rolled value of the attack bonus (once per attack).

I think we can reach what you've suggested by having a button to roll the attack bonus which displays the result in chat and stores it in a hidden field.

Then we provide a similar mechanism to allow the To Hit and Damage rolls to access that stored value (instead of the current value that exists for the duration of the attack roll function).

**Comment by wesbaker** [comment]
Could you give me an example of how this works?
